export enum SignalCategory {
  BreakthroughMaterial = "breakthrough_material",
  NewFabricationMethod = "new_fabrication_method",
  MuseumAcquisition = "museum_acquisition",
  ArtistInnovation = "artist_innovation",
  AiToolRelease = "3d_ai_tool_release",
  MarketTrend = "market_trend",
  ResearchPaper = "research_paper",
  EventOrBiennale = "event_or_biennale",
}

export interface Signal {
  title: string;
  link: string; // Used for display, generated by AI as simulation
  source: string;
  published: string;
  category: SignalCategory;
  weight: number;
  score: number;
  summary: string;
}

export interface WatchtowerReport {
  timestamp: string;
  pressure_index: number;
  signals: Signal[];
}

export type ViewMode = 'dashboard' | 'signals' | 'oracle';